### PR TITLE
Added regex parser as valid parsing algorithm

### PR DESCRIPTION
**Pull request by iglocska**

### CODE REVIEW

**Comment by Rafiot** [comment]
Which kind of regex is expected? PCRE? I should add it in the search method

**Comment by iglocska** [comment]
Good point. PCRE, but started reading up on the PHP -> Python conversion
and it's not that straight forward. Will do something about it over the
weekend.

**Comment by iglocska** [comment]
Added the search, it will convert PHP style regex to Python style ones using the modifiers that make sense in Python.

**Comment by Rafiot** [comment]
Do we have a test case by any chance? That would be helpful to make sure it works okay.

**Pull request closed without merging**
